### PR TITLE
Modified currency-symbols.constants reference

### PR DESCRIPTION
**Pull request by tigsinthetrees**
Modified currency-symbols.constants reference to _constants because the file name has changed and the original caused the program to fail

### CODE REVIEW

**Review by prasidmitra — APPROVED** [review]

**Comment by PetrNovota** [comment]
can we merge this PR?

**Comment by snoopyjc** [comment]
Some of the tests are failing and I’m trying to get it all to run on Python 3.10. Please stand by. 

-joe

**Comment by snoopyjc** [comment]
Ok - I'm getting close - had to add a dependency for chardat, otherwise UnicodeDammit does a really poor job

**Comment by snoopyjc** [comment]
Installed this fix in v0.2.0 - thank you for your PR

**Comment by snoopyjc** [comment]
v0.2.0 is released!!  Sorry about the delay. 

-joe

**Comment by PetrNovota** [comment]
@snoopyjc oh, thank you :)

**Pull request closed without merging**
