### PR TITLE
feat:add ignore workbook corruption error

### PR DESCRIPTION
**Pull request by Stitch-Zhang**
This feat can fix `xlrd.compdoc.CompDocError: Workbook corruption: seen[2] == 4` error  which xls file may be too old or something else  
I have tested this code for the file which are `Workbook corruption`  and converted successfully

### CODE REVIEW

**Comment by snoopyjc** [comment]
Thanks!

Can you add a test case for this update please?

-Joe

**Comment by Stitch-Zhang** [comment]
Sorry for my poor skills ,the code of test case may be unsuitable
It is appreciated that if you can improve this test case

**Comment by snoopyjc** [comment]
Sorry for the delay but I'm merging this fix into my latest version - one problem - your workbook_corruption.xls is NOT corrupted.  I did made a corrupted file (by putting the .xls into vi and changing some bytes),  but that workbook can't be read at all.  I fixed the code to silently handle that and return None from excel.to_xlsx().  Can you supply one where xlrd can read it if you supply ignore_workbook_corruption=True to it?

**Comment by snoopyjc** [comment]
Never mind - I went to the github for xlrd and got a corrupted input test case

**Comment by snoopyjc** [comment]
Installed this fix in v0.2.0 - thank you for your PR

**Pull request closed without merging**
